/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.umt.struts.action;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.umt.struts.form.LoignForm;
import com.umt.struts.vo.Dept;
import com.umt.struts.vo.Student;

/** 
 * MyEclipse Struts
 * Creation date: 10-27-2009
 * 
 * XDoclet definition:
 * @struts.action path="/loign" name="loignForm" input="/loign.jsp" parameter="method" scope="request" validate="true"
 */
public class LoignAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoignForm loignForm = (LoignForm) form;// TODO Auto-generated method stub
		String url = "";
		
		if(loignForm.getUsername().equals("admin") && loignForm.getPwd().equals("123")){
			request.setAttribute("msg", "Login Success!!");
			request.setAttribute("time", new Date());
			Student stu = new Student(1,"yexu");
			stu.setDept(new Dept("计算机科学与技术"));
			
			
			Student stu2 = new Student(2,"aaa");
			stu2.setDept(new Dept("计算机科学与技术"));
			
			
			Student stu3 = new Student(3,"bbb");
			stu3.setDept(new Dept("计算机科学与技术"));
			
			List students = new ArrayList();
			students.add(stu);
			students.add(stu2);
			students.add(stu3);
			
			
			request.setAttribute("stu", stu);
			request.setAttribute("students", students);
			url = "success";
		}else{
			url = "login";
		}
		return mapping.findForward(url);
	}
}