/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.umt.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import com.umt.form.LoginForm;
import com.umt.service.TestService;
import com.umt.vo.Test;

/** 
 * MyEclipse Struts
 * Creation date: 11-13-2009
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/form/login.jsp" parameter="method" scope="request" validate="true"
 */
public class LoginAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	
	private TestService testService;
	
	

	public void setTestService(TestService testService) {
		this.testService = testService;
	}



	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm loginForm = (LoginForm) form;
		
		Test test = testService.isLogin(loginForm.getUserName(), loginForm.getPwd());
		
		String url = "";
		if(test != null){
			url = "success";
		}else{
			url = "login";
		}
		return mapping.findForward(url);
	}
}